export const environment = {
  production: false,
  environment: "Development",
  base_url_api: "http://localhost:3000/api",
  base_url_users: "/users/",
  base_url_login_users: "/users/login/",
  base_url_cities: "/cities/",
  base_url_attractions: "/attractions/",
  authorization_header_name:"authorization",
  authorization_bearer: "Bearer ",
  token_name: "token",
  path_root: "",
  path_cities: "cities",
  path_register: "register",
  path_login: "login",
  path_add_city: "addCity",
  path_city: "city/:cityId",
  path_update_city: "updatecity/:cityId",
  path_aupdate_attraction: "updateattraction/:cityId/:attractionId",
  path_add_attraction: "addAttraction/:cityId",
  path_error_page: "**",
  city_id_tag:"cityId",
  city_route:"/city/",
  attraction_id_tag:"attractionId"
};
